### ISSUE TITLE
OCbuilder does not finish

### ISSUE THREAD

**Issue by startergo** [Pavo-IM/ocbuilder#5] opened 2019-11-13 17:17 UTC
In Catalina 10.15.1 The builder stops at line:
Cloning OpenCorePkg SupportPkgs into UDK...
It worked before for me. I also tried building opencore directly but there I have a bunch of errors:
`In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:64:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:93:16: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
      [-Werror,-Wnullability-completeness]
        unsigned char   *_base;
                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:93:16: note: insert '_Nullable' if the pointer may be null
        unsigned char   *_base;
                        ^
                          _Nullable 
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:93:16: note: insert '_Nonnull' if the pointer should never be null
        unsigned char   *_base;
                        ^
                          _Nonnull 
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:138:32: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
      [-Werror,-Wnullability-completeness]
        int     (* _Nullable _read) (void *, char *, int);
                                          ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:138:32: note: insert '_Nullable' if the pointer may be null
        int     (* _Nullable _read) (void *, char *, int);
                                          ^
                                           _Nullable
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:138:32: note: insert '_Nonnull' if the pointer should never be null
        int     (* _Nullable _read) (void *, char *, int);
                                          ^
                                           _Nonnull
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:138:40: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
      [-Werror,-Wnullability-completeness]
        int     (* _Nullable _read) (void *, char *, int);
                                                  ^
`In Mojave it finishes without issues

**Comment by Pavo-IM** [comment] 2019-11-14 19:56
Working fine here no issues, please run the executable inside the app bundle in terminal and show me logs.

**Comment by zirkaiva** [comment] 2019-11-15 14:25
> Working fine here no issues, please run the executable inside the app bundle in terminal and show me logs.

`Last login: Fri Nov 15 08:51:45 on ttys000
/Users/usr/Downloads/OCBuilder.app/Contents/MacOS/OCBuilder ; exit;
➜  ~ /Users/usr/Downloads/OCBuilder.app/Contents/MacOS/OCBuilder ; exit;
Password:Cloning into 'Lilu'...
remote: Enumerating objects: 144, done.
remote: Counting objects: 100% (144/144), done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 3700 (delta 74), reused 78 (delta 40), pack-reused 3556
Receiving objects: 100% (3700/3700), 4.26 MiB | 8.77 MiB/s, done.
Resolving deltas: 100% (2153/2153), done.
Cloning into 'AppleALC'...
remote: Enumerating objects: 68, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 10881 (delta 31), reused 25 (delta 5), pack-reused 10813
Receiving objects: 100% (10881/10881), 19.95 MiB | 15.86 MiB/s, done.
Resolving deltas: 100% (5973/5973), done.
Cloning into 'WhateverGreen'...
remote: Enumerating objects: 81, done.
remote: Counting objects: 100% (81/81), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 1584 (delta 44), reused 46 (delta 24), pack-reused 1503
Receiving objects: 100% (1584/1584), 2.53 MiB | 7.84 MiB/s, done.
Resolving deltas: 100% (973/973), done.
Cloning into 'VirtualSMC'...
remote: Enumerating objects: 1393, done.
remote: Total 1393 (delta 0), reused 0 (delta 0), pack-reused 1393
Receiving objects: 100% (1393/1393), 3.58 MiB | 8.36 MiB/s, done.
Resolving deltas: 100% (915/915), done.
Cloning into 'CPUFriend'...
remote: Enumerating objects: 90, done.
remote: Counting objects: 100% (90/90), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 415 (delta 42), reused 55 (delta 18), pack-reused 325
Receiving objects: 100% (415/415), 148.95 KiB | 3.63 MiB/s, done.
Resolving deltas: 100% (214/214), done.
Cloning into 'AirportBrcmFixup'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 807 (delta 12), reused 14 (delta 2), pack-reused 776
Receiving objects: 100% (807/807), 1.70 MiB | 4.82 MiB/s, done.
Resolving deltas: 100% (425/425), done.
Cloning into 'ATH9KFixup'...
remote: Enumerating objects: 235, done.
remote: Total 235 (delta 0), reused 0 (delta 0), pack-reused 235
Receiving objects: 100% (235/235), 1.19 MiB | 3.93 MiB/s, done.
Resolving deltas: 100% (106/106), done.
Cloning into 'BT4LEContinuityFixup'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 157 (delta 1), reused 0 (delta 0), pack-reused 151
Receiving objects: 100% (157/157), 80.42 KiB | 2.06 MiB/s, done.
Resolving deltas: 100% (71/71), done.
Cloning into 'DiskArbitrationFixup'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 26 (delta 2), reused 2 (delta 0), pack-reused 18
Unpacking objects: 100% (26/26), done.
Cloning into 'HibernationFixup'...
remote: Enumerating objects: 64, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 647 (delta 37), reused 28 (delta 7), pack-reused 583
Receiving objects: 100% (647/647), 1.10 MiB | 4.97 MiB/s, done.
Resolving deltas: 100% (334/334), done.
Cloning into 'NoTouchID'...
remote: Enumerating objects: 32, done.
remote: Total 32 (delta 0), reused 0 (delta 0), pack-reused 32
Unpacking objects: 100% (32/32), done.
Cloning into 'RTCMemoryFixup'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 133 (delta 4), reused 6 (delta 2), pack-reused 118
Receiving objects: 100% (133/133), 118.99 KiB | 1.47 MiB/s, done.
Resolving deltas: 100% (46/46), done.
Cloning into 'IntelMausiEthernet'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 336 (delta 0), reused 4 (delta 0), pack-reused 328
Receiving objects: 100% (336/336), 492.43 KiB | 2.83 MiB/s, done.
Resolving deltas: 100% (175/175), done.
Cloning into 'AtherosE2200Ethernet'...
remote: Enumerating objects: 257, done.
remote: Total 257 (delta 0), reused 0 (delta 0), pack-reused 257
Receiving objects: 100% (257/257), 214.73 KiB | 1.87 MiB/s, done.
Resolving deltas: 100% (124/124), done.
Cloning into 'RTL8111_driver_for_OS_X'...
remote: Enumerating objects: 698, done.
remote: Total 698 (delta 0), reused 0 (delta 0), pack-reused 698
Receiving objects: 100% (698/698), 1.70 MiB | 5.41 MiB/s, done.
Resolving deltas: 100% (330/330), done.
Cloning into 'TSCAdjustReset'...
remote: Enumerating objects: 34, done.
remote: Total 34 (delta 0), reused 0 (delta 0), pack-reused 34
Unpacking objects: 100% (34/34), done.
In file included from BasePeCoff.c:12:
In file included from ../Common/CommonLib.h:439:
In file included from /usr/local/include/stdio.h:64:
/usr/local/include/_stdio.h:93:16: error: pointer is missing a nullability type
      specifier (_Nonnull, _Nullable, or _Null_unspecified)
      [-Werror,-Wnullability-completeness]
        unsigned char   *_base;
                        ^
/usr/local/include/_stdio.h:93:16: note: insert '_Nullable' if the pointer may
      be null
        unsigned char   *_base;
                        ^
                          _Nullable 
/usr/local/include/_stdio.h:93:16: note: insert '_Nonnull' if the pointer should
      never be null
        unsigned char   *_base;
                        ^
                          _Nonnull 
/usr/local/include/_stdio.h:138:32: error: pointer is missing a nullability type
      specifier (_Nonnull, _Nullable, or _Null_unspecified)
      [-Werror,-Wnullability-completeness]
        int     (* _Nullable _read) (void *, char *, int);
                                          ^
/usr/local/include/_stdio.h:138:32: note: insert '_Nullable' if the pointer may
      be null
        int     (* _Nullable _read) (void *, char *, int);
                                          ^
                                           _Nullable
/usr/local/include/_stdio.h:138:32: note: insert '_Nonnull' if the pointer
      should never be null
        int     (* _Nullable _read) (void *, char *, int);
                                          ^
                                           _Nonnull
/usr/local/include/_stdio.h:138:40: error: pointer is missing a nullability type
      specifier (_Nonnull, _Nullable, or _Null_unspecified)
      [-Werror,-Wnullability-completeness]
        int     (* _Nullable _read) (void *, char *, int);
                                                  ^
/usr/local/include/_stdio.h:138:40: note: insert '_Nullable' if the pointer may
      be null
        int     (* _Nullable _read) (void *, char *, int);
                                                  ^
                                                   _Nullable
/usr/local/include/_stdio.h:138:40: note: insert '_Nonnull' if the pointer
      should never be null
        int     (* _Nullable _read) (void *, char *, int);
                                                  ^
                                                   _Nonnull
/usr/local/include/_stdio.h:139:35: error: pointer is missing a nullability type
      specifier (_Nonnull, _Nullable, or _Null_unspecified)
      [-Werror,-Wnullability-completeness]
        fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
                                          ^
/usr/local/include/_stdio.h:139:35: note: insert '_Nullable' if the pointer may
      be null
        fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
                                          ^
                                           _Nullable
/usr/local/include/_stdio.h:139:35: note: insert '_Nonnull' if the pointer
      should never be null
        fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
                                          ^
                                           _Nonnull
/usr/local/include/_stdio.h:140:32: error: pointer is missing a nullability type
      specifier (_Nonnull, _Nullable, or _Null_unspecified)
      [-Werror,-Wnullability-completeness]
        int     (* _Nullable _write)(void *, const char *, int);
                                          ^
/usr/local/include/_stdio.h:140:32: note: insert '_Nullable' if the pointer may
      be null
        int     (* _Nullable _write)(void *, const char *, int);
                                          ^
                                           _Nullable
/usr/local/include/_stdio.h:140:32: note: insert '_Nonnull' if the pointer
      should never be null
        int     (* _Nullable _write)(void *, const char *, int);
                                          ^
                                           _Nonnull
/usr/local/include/_stdio.h:140:46: error: pointer is missing a nullability type
      specifier (_Nonnull, _Nullable, or _Null_unspecified)
      [-Werror,-Wnullability-completeness]
        int     (* _Nullable _write)(void *, const char *, int);
                                                        ^
/usr/local/include/_stdio.h:140:46: note: insert '_Nullable' if the pointer may
      be null
        int     (* _Nullable _write)(void *, const char *, int);
                                                        ^
                                                         _Nullable
/usr/local/include/_stdio.h:140:46: note: insert '_Nonnull' if the pointer
      should never be null
        int     (* _Nullable _write)(void *, const char *, int);
                                                        ^
                                                         _Nonnull
/usr/local/include/_stdio.h:144:18: error: pointer is missing a nullability type
      specifier (_Nonnull, _Nullable, or _Null_unspecified)
      [-Werror,-Wnullability-completeness]
        struct __sFILEX *_extra; /* additions to FILE to not break ABI */
                        ^
/usr/local/include/_stdio.h:144:18: note: insert '_Nullable' if the pointer may
      be null
        struct __sFILEX *_extra; /* additions to FILE to not break ABI */
                        ^
                          _Nullable 
/usr/local/include/_stdio.h:144:18: note: insert '_Nonnull' if the pointer
      should never be null
        struct __sFILEX *_extra; /* additions to FILE to not break ABI */
                        ^
                          _Nonnull 
In file included from BasePeCoff.c:12:
In file included from ../Common/CommonLib.h:439:
/usr/local/include/stdio.h:67:13: error: pointer is missing a nullability type
      specifier (_Nonnull, _Nullable, or _Null_unspecified)
      [-Werror,-Wnullability-completeness]
extern FILE *__stdinp;
            ^
/usr/local/include/stdio.h:67:13: note: insert '_Nullable' if the pointer may be
      null
extern FILE *__stdinp;
            ^
              _Nullable 
/usr/local/include/stdio.h:67:13: note: insert '_Nonnull' if the pointer should
      never be null
extern FILE *__stdinp;
            ^
              _Nonnull 
/usr/local/include/stdio.h:386:41: error: pointer is missing a nullability type
      specifier (_Nonnull, _Nullable, or _Null_unspecified)
      [-Werror,-Wnullability-completeness]
                 int (* _Nullable)(void *, const char *, int),
                                        ^
/usr/local/include/stdio.h:386:41: note: insert '_Nullable' if the pointer may
      be null
                 int (* _Nullable)(void *, const char *, int),
                                        ^
                                         _Nullable
/usr/local/include/stdio.h:386:41: note: insert '_Nonnull' if the pointer should
      never be null
                 int (* _Nullable)(void *, const char *, int),
                                        ^
                                         _Nonnull
/usr/local/include/stdio.h:386:55: error: pointer is missing a nullability type
      specifier (_Nonnull, _Nullable, or _Null_unspecified)
      [-Werror,-Wnullability-completeness]
                 int (* _Nullable)(void *, const char *, int),
                                                      ^
/usr/local/include/stdio.h:386:55: note: insert '_Nullable' if the pointer may
      be null
                 int (* _Nullable)(void *, const char *, int),
                                                      ^
                                                       _Nullable
/usr/local/include/stdio.h:386:55: note: insert '_Nonnull' if the pointer should
      never be null
                 int (* _Nullable)(void *, const char *, int),
                                                      ^
                                                       _Nonnull
/usr/local/include/stdio.h:387:44: error: pointer is missing a nullability type
      specifier (_Nonnull, _Nullable, or _Null_unspecified)
      [-Werror,-Wnullability-completeness]
                 fpos_t (* _Nullable)(void *, fpos_t, int),
                                           ^
/usr/local/include/stdio.h:387:44: note: insert '_Nullable' if the pointer may
      be null
                 fpos_t (* _Nullable)(void *, fpos_t, int),
                                           ^
                                            _Nullable
/usr/local/include/stdio.h:387:44: note: insert '_Nonnull' if the pointer should
      never be null
                 fpos_t (* _Nullable)(void *, fpos_t, int),
                                           ^
                                            _Nonnull
/usr/local/include/stdio.h:388:41: error: pointer is missing a nullability type
      specifier (_Nonnull, _Nullable, or _Null_unspecified)
      [-Werror,-Wnullability-completeness]
                 int (* _Nullable)(void *));
                                        ^
/usr/local/include/stdio.h:388:41: note: insert '_Nullable' if the pointer may
      be null
                 int (* _Nullable)(void *));
                                        ^
                                         _Nullable
/usr/local/include/stdio.h:388:41: note: insert '_Nonnull' if the pointer should
      never be null
                 int (* _Nullable)(void *));
                                        ^
                                         _Nonnull
/usr/local/include/stdio.h:384:6: error: pointer is missing a nullability type
      specifier (_Nonnull, _Nullable, or _Null_unspecified)
      [-Werror,-Wnullability-completeness]
FILE    *funopen(const void *,
        ^
/usr/local/include/stdio.h:384:6: note: insert '_Nullable' if the pointer may be
      null
FILE    *funopen(const void *,
        ^
          _Nullable 
/usr/local/include/stdio.h:384:6: note: insert '_Nonnull' if the pointer should
      never be null
FILE    *funopen(const void *,
        ^
          _Nonnull 
13 errors generated.
make[2]: *** [BasePeCoff.o] Error 1
make[1]: *** [Common] Error 2
make: *** [Source/C] Error 2

`

**Comment by Pavo-IM** [comment] 2019-11-15 18:37
Ok this looks like there is some kind of issue with the building of TSCAdjustReset repo, I’ll take a look at the command that is building that specific repo and see if I can replicate your issue.

**Comment by startergo** [comment] 2019-11-15 20:26
But the same issue exists when building OC directly from the GIT code. It looks more like Xcode issue, particularly linking stdio.h library in the compiler path. Are your stdio.h files under the same folder names?

**Comment by Pavo-IM** [comment] 2019-11-15 21:23
Then maybe it has something to do with your install of Xcode because as you can see in the movie I just posted it working as intended.

https://www.dropbox.com/s/w1ci6dhxhryi2zu/Screen%20Recording%202019-11-15%20at%204.16.39%20PM.mov?dl=0

**Comment by r3dlobst3r** [comment] 2019-11-22 14:14
I am having an issue with it not finishing also. I figured I would hop on here instead of opening a new issue.

> The following build commands failed:
	CompileC /tmp/OCBuilder_Clone/DiskArbitrationFixup/build/DiskArbitrationFixup.build/Release/DiskArbitrationFixup.build/Objects-normal/x86_64/kern_start.o /tmp/OCBuilder_Clone/DiskArbitrationFixup/DiskArbitrationFixup/kern_start.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by Pavo-IM** [comment] 2019-11-22 14:16
Will look into this, looks like its missing the debug version of Lilu, which "should" get copied to all Lilu plugins after compiling Lilu at the beginning of the script.

**Comment by Pavo-IM** [comment] 2019-11-22 16:12
Latest Lilu commits have broken a few of the Lilu plugins, I have removed those from the building process, will put back once they are fixed. Update to latest release 3.1 and everything should work fine.

**Closed by Pavo-IM** 2019-11-22 16:12 UTC
